server:
  port: 8090

#服务注册中心配置
eureka:
  client:
    serviceUrl:
      #这个地址填的是注册中心eureka-server的地址
      defaultZone: http://localhost:8081/eureka/
    healthcheck:
      enabled: true

spring :
  application:
    name: controller